name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        env:
          FUNCTION_NAME: aws-lambda-typescript-template-function
        run: |
          npx ncc build ./src/index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=${FUNCTION_NAME} --zip-file=fileb://deploy.zip
